import { Geist, Geist_Mono, Sansation } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sansation = Sansation({
  subsets: ["latin"],
  weight: ["300", "400", "700"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sansation.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
